#!/usr/bin/env python

import math
import os
import random
import re
import sys


def jumpingOnClouds(c):
    count = 0
    current = 0
    end = len(c) - 1
    while current < end:
        if ((current + 2) <= end) and c[current + 2] == 0:
            current += 2
        else:
            current += 1
        count += 1
    return count


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')
    n = int(input())
    c = list(map(int, input().rstrip().split()))
    result = jumpingOnClouds(c)
    fptr.write(str(result) + '\n')
    fptr.close()
