#!/usr/bin/env node
'use strict';

process.stdin.resume();
process.stdin.setEncoding('utf-8');

let inputString = '';
let currentLine = 0;

process.stdin.on('data', inputStdin => {
  inputString += inputStdin;
});

process.stdin.on('end', function() {
  inputString = inputString
    .replace(/\s*$/, '')
    .split('\n')
    .map(str => str.replace(/\s*$/, ''));

  main();
});

function readLine() {
  return inputString[currentLine++];
}

function checkMagazine(magazine, note) {
  const count = a =>
    a.reduce((h, x) => {
      h.set(x, h.get(x) ? h.get(x) + 1 : 1);
      return h;
    }, new Map());

  const magazineCounts = count(magazine);
  const noteCounts = count(note);

  for (let [n, c] of noteCounts) {
    if (!magazineCounts.has(n) || magazineCounts.get(n) < c) {
      console.log('No');
      return;
    }
  }

  console.log('Yes');
}

function main() {
  const mn = readLine().split(' ');
  const m = parseInt(mn[0], 10);
  const n = parseInt(mn[1], 10);
  const magazine = readLine().split(' ');
  const note = readLine().split(' ');
  checkMagazine(magazine, note);
}
