#!/usr/bin/env python

import math
import os
import random
import re
import sys


def countingValleys(n, s):
    level = 0
    valleys = 0
    for step in s:
        if 'D' == step:
            level -= 1
        elif 'U' == step:
            level += 1
            if 0 == level:
                valleys += 1
    return valleys


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')
    n = int(input())
    s = input()
    result = countingValleys(n, s)
    fptr.write(str(result) + '\n')
    fptr.close()
