#!/usr/bin/env python

import math
import os
import random
import re
import sys


def sockMerchant(n, ar):
    count = 0
    pairs = set()
    for num in ar:
        if num in pairs:
            count += 1
            pairs.discard(num)
        else:
            pairs.add(num)
    return count


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')
    n = int(input())
    ar = list(map(int, input().rstrip().split()))
    result = sockMerchant(n, ar)
    fptr.write(str(result) + '\n')
    fptr.close()
